export const FETCH_LIST_SUCCESS = "FETCH_LIST_SUCCESS";
export const FETCH_FILTER_SUCCESS = "FETCH_FILTER_SUCCESS";
export const FETCH_ID_SUCCESS = "FETCH_ID_SUCCESS";
export const FETCH_ID_NULL = "FETCH_ID_NULL";